package updatedVariant;

/**
 * In this class the program logic is demonstrated.
 * This class contains various methods for providing comparison of the typed user's value
 * with the random value in the range [min;max].
 *
 * @author Pidhurska Tetiana
 * @version 2 (updated on 14.05.16)
 */

public class Model2 {

    /**
     * The valueMaschine is used for storage of value generated by machine using random()
     * The valueUser is the parameter that the user enters attempting to guess the valueMaschine
     * min, max are the parameters of the input range inclusively in which the valueMaschine is generated
     */
    private int valueMaschine, min, max;



    /**
     * Returns the randomly generated integer  of its arguments,
     * in this method generateRandomValue() the random value is generated between 0 and max=100
     *
     * @return a pseudorandom {@code int}
     */
    public int generateRandomValue() {
        valueMaschine = (int) Math.ceil(Math.random() * (max - min - 1) + min);
        return valueMaschine;
    }

    /**
     * returns the boolean result of comparison:
     * of the  entered by user value with  the generated random value
     */
    public boolean checkValue(int value) {
        if (value == valueMaschine) {
            return true;
        } else if (value > valueMaschine) {
            max = value;
        } else {
            min = value;
        }
        return false;
    }


    public int getMin() {
        return min;
    }

    public int getMax() {
        return max;
    }

    public int getValueMaschine() {
        return valueMaschine;
    }

    public void setMinMaxRangeValues(int min,int max) {
        this.min = min;
        this.max = max;

    }
}
