
/**
 * In this class the program logic is demonstrated.
 * This class contains various methods for providing comparison of the typed user's value
 * with the random value in the range [min;max].
 *
 * @author Pidhurska Tetiana
 * @version 2 (updated on 26.04.16)
 */

public class Model2 {

    /**
     * The valueMaschine is used for storage of value generated by machine using random()
     * The valueUser is the parameter that the user enters attempting to guess the valueMaschine
     * min, max are the parameters of the input range inclusively in which the valueMaschine is generated
     */
    private int valueMaschine, valueUser, min = 0, max = 100;

    /**
     * Initializes a newly created object so that it represents
     * the randomly generated integer value
     */
    public Model2() {
        this.valueMaschine = generateRandomValue();
    }

    /**
     * Returns the randomly generated integer  of its arguments,
     * in this method generateRandomValue() the random value is generated between 0 and max=100
     *
     * @return a pseudorandom {@code int}
     */
    public int generateRandomValue() {
        valueMaschine = (int) Math.round(Math.random() * max);
        return valueMaschine;
    }

    /**
     * returns the boolean result of comparison:
     * of the  entered by user value with  the generated random value
     */
    public boolean valEquals() {
        // if the generated value is not equal to the value, entered by user
        return (valueMaschine == valueUser);
    }

    /**
     * The random value is compared with the value entered by user
     * on the criterion less or more.
     * The new values of range are defined according to the result of comparison
     */
    public boolean greaterMashineValue() {
        if (valueMaschine < valueUser) {
            max = valueUser;
            return false;
        } else {
            min = valueUser;
            return true;
        }
    }

    public int getMin() {
        return min;
    }

    public int getMax() {
        return max;
    }

    public int getValueUser() {
        return valueUser;
    }

    public void setValueUser(int valueUser) {
        this.valueUser = valueUser;
    }

    public int getValueMaschine() {
        return valueMaschine;
    }
}
